### ISSUE TITLE
Fabric Version Can't Be Used

### ISSUE THREAD

**Issue by TheWhistlers** [Frinn38/Custom-Machinery-Create#2]
Hello.
I found a problem that, in the farbic version, I can't use this mod.
Because this mod requires the create whose version is 0.5.0.i
But I can't download that whatever in CurseForge or Modrinth.
I think there is something wrong in the create's version requirement
Hope this be solved soon

ps:1.18.2-fabric

**Comment by TheWhistlers** [comment]
the version CustomMachineryCreate-1.0.1 and the Create-0.5.1.a are suitable
but the version CustomMachineryCreate-1.0.0 isn't

**Comment by Frinn38** [comment]
Should be fixed in latest version, use Custom Machinery Create 1.0.2 with any version of Create Fabric.
