### ISSUE TITLE
[Bug]Game crash when use Custom Machinery Create

### ISSUE THREAD

**Issue by Alan-Yan-CanMeng** [Frinn38/Custom-Machinery-Create#3]
Custom Machinery version: 1.19.2-0.9.10
Custom Machinery Create version: 1.19.2-1.1.0
Crash report: https://mclo.gs/fjVYMQ4

**Comment by Frinn38** [comment]
There was indeed some incompatibility between the create and the botania addons.
A new version of CM botania just has been released, update it and that crash shouldn't happen again.
