### ISSUE TITLE
[1.19.2] Getting a CME when trying to shut down the game or server when running a per fluid tick recipe

### ISSUE THREAD

**Issue by Saereth** [Frinn38/Custom-Machinery-Create#4]
I'm running a recipe that consume 1mb of diesel per tick and prduces SU. Everything seems to be working fine but during shutdown there is a concurrency issue happening sometimes that causes the server/client to just hang indefinitely and go into a loop. 

You can see the issue at the end of the log here:
https://gist.github.com/Saereth/a55c44aa8e7034cdcbe50cd1ef39647c

I wasnt sure if this is an issue with custom machinery or the create addon specifically but if I need to post this somewhere else let me know. If I can provide any additional information please let me know.

MC 1.19.2
Forge 43.3.8
Create1.19.2-0.5.1.f
Custom Machinery: CustomMachinery-forge-1.19.2-0.9.10
+ CustomMachineryCreate-forge-1.19.2-1.1.0

I'm defining my recipes kubejs as follows:

```
function dieselGeneratorRecipe(event, duration, id, priority) {
  const recipe = event.recipes.custommachinery
    .custom_machine("ftbskies:diesel_generator", duration)
  return {
    fluidTagInput(tag, amount) {
      recipe.requireFluidTag(tag, amount, "inputtank1");
      return this;
    },
    stressOutput(rpm, stress) {
      recipe.produceSU(rpm, stress);
      return this;
    },
    build() {
      recipe.requireRedstone(0)
      recipe.priority(priority);
      recipe.jei();
      recipe.id(id);
    },
  };
}


//tag, SU Production, burnrate
const fuelMap = [
  ["forge:biodiesel", 22, 2],
  ["forge:diesel", 32, 2],
  ["forge:flux_diesel", 85, 1],
  ["forge:force_biodiesel", 32, 1],
  ["forge:force_diesel", 42, 1],
]

ServerEvents.recipes((event) => {
  fuelMap.forEach((fuel) => {
    dieselGeneratorRecipe(event, 20, `ftbskies:diesel_su_gen_${fuel[0].split(":")[1]}`, 1)
      .fluidTagInput(fuel[0], fuel[2])
      .stressOutput(96, fuel[1])
      .build();

  });
)}
```

If I apply a redstone signal to stop the recipes from processing and save/edit it does so without issue. 
if I comment out the recipe.produceSU(rpm, stress); it also closes without issue so looks like its trying to possibly update the SU network during shutdown causing a chunks to attempt to spam reload/shutdown (best guess)

**Comment by Frinn38** [comment]
It's indeed an issue with the Create add-on, and indeed the unloading of the machine when the chunk is unloaded triggers an update of the kinetic network which try to load a chunk (the one that contains the machine or another one next to it idk) resulting in the game waiting indefinitely for a chunk that won't be loaded anyway.
I can't fix this issue without updating the main mod, but that should happen soon, I have 2-3 things to finish before the update and after that I will fix this issue in the add-on.
