### ISSUE TITLE
[Bug] Stress Capacity dupe

### ISSUE THREAD

**Issue by TheonlyTazz** [Frinn38/Custom-Machinery-Create#5]
MC 1.19.2
Forge 43.3.5
Create1.19.2-0.5.1.f
Custom Machinery: CustomMachinery-forge-1.19.2-0.9.12
Custom Machinery Create: CustomMachineryCreate-forge-1.19.2-1.1.1
Modpack: FTB Skies Expert
---

Custom Machines that generate SU will not properly update the network on a server restart (or Singleplayer quit game) when the Create Network spans over multiple chunks.

Upon restart; the Stress Units are doubled untill the network is updated by breaking/replacing a block or by `.remove()`-ing the fakeblock.

https://github.com/Frinn38/Custom-Machinery-Create/assets/3908847/6002cefa-9611-4cc4-8c04-2b4c61a51174

NOTE: i used a KubeJS script to get the fakeTile to `.remove()` itself from the network (triggered by rightclicking the stick) which, as shown, fixes the issue.

![image](https://github.com/Frinn38/Custom-Machinery-Create/assets/3908847/13851d3d-c2a1-4334-ac46-c4988730c7ce)

**Comment by Frinn38** [comment]
I don't like the way I fixed this, especially because I didn't completely understood what caused this issue.
But since the fix seems to work that will do it.
